/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ProdutoDAO;
import DAO.Tipo_produtoDAO;
import DTO.ProdutoDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author mardio
 */
public class FrmProdutoVIEW extends javax.swing.JFrame {

    Vector<Integer> mov_id = new Vector<>();
    String varStatus;

    /**
     * Creates new form FrmProdutoVIEW
     */
    public FrmProdutoVIEW() {
        initComponents();
        restaurarDadosComboBoxTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Status = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbAtivado = new javax.swing.JCheckBox();
        jcbDesativado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtEstoqueMinimo = new javax.swing.JTextField();
        txtEstoqueMaximo = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbxTipoProduto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/produto48.png"))); // NOI18N
        jLabel1.setText("Cadastro de Produtos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 442, 57));

        jLabel2.setText("Produto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 101, -1, -1));

        jLabel3.setText("Status:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Status.add(jcbAtivado);
        jcbAtivado.setText("Ativado");
        jPanel1.add(jcbAtivado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        Status.add(jcbDesativado);
        jcbDesativado.setText("Desativado");
        jPanel1.add(jcbDesativado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel4.setText("Estoque Mínimo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setText("Estoque Máximo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 231, -1));
        jPanel1.add(txtEstoqueMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 61, -1));
        jPanel1.add(txtEstoqueMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 61, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel6.setText("Tipo Produto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cbxTipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jPanel1.add(cbxTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrarProduto();
        limpar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Status;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbxTipoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbAtivado;
    private javax.swing.JCheckBox jcbDesativado;
    private javax.swing.JTextField txtEstoqueMaximo;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
public void restaurarDadosComboBoxTipo() {
        try {
            Tipo_produtoDAO objTipo_produtoDAO = new Tipo_produtoDAO();
            ResultSet rs = objTipo_produtoDAO.listarTipo();
            while (rs.next()) {
                mov_id.addElement(rs.getInt(1));
                cbxTipoProduto.addItem(rs.getString(2));
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Carregar Tipo" + erro);
        }

    }

    public void cadastrarProduto() {
        if (Status.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Status é um campo Obrigatorio!!!");
        } else {
            if (jcbAtivado.isSelected()) {
                varStatus = "Ativado";
            }
            if (jcbDesativado.isSelected()) {
                varStatus = "Desativado";
            }
            if (txtProduto.getText().isEmpty() || txtEstoqueMinimo.getText().isEmpty() || txtEstoqueMaximo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Favor Preencher todos os Campos!!!");

            } else {
                int codtipo = mov_id.get(cbxTipoProduto.getSelectedIndex() - 1);
//                JOptionPane.showMessageDialog(null, codtipo);
                ProdutoDTO objProdutoDTO = new ProdutoDTO();
                objProdutoDTO.setPro_descricao(txtProduto.getText());
                objProdutoDTO.setPro_fkidtipo(codtipo);
                objProdutoDTO.setPro_status(varStatus);
                objProdutoDTO.setPro_estoque_minimo(Integer.parseInt(txtEstoqueMinimo.getText()));
                objProdutoDTO.setPro_estoque_maximo(Integer.parseInt(txtEstoqueMaximo.getText()));
                ProdutoDAO objProdutoDAO = new ProdutoDAO();
                objProdutoDAO.cadastrarUsuario(objProdutoDTO);
            }

        }
    }
    public void limpar(){
        txtEstoqueMaximo.setText("");
        txtEstoqueMinimo.setText("");
        txtProduto.setText("");
        Status.clearSelection();
        cbxTipoProduto.setSelectedIndex(0);
    }
}
