/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ModuloConexao;
import UTIL.NumeroValorUTIL;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mardio
 */
public class FrmSaidaProdutoVIEW1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmEntradaProdutoVIEW
     */
    public FrmSaidaProdutoVIEW1() {
        initComponents();
        tabela.setDefaultRenderer(Object.class, new CellRenderer());
        txtIdProduto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackgroud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtIdProduto = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtDataEntrada = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpBackgroud.setBackground(new java.awt.Color(255, 255, 255));
        jpBackgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrada de Produto");
        jpBackgroud.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 453, 38));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "...", "...", "...", "..."
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(50);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela.getColumnModel().getColumn(1).setMinWidth(0);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(0);
            tabela.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jpBackgroud.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 222, 429, 97));
        jpBackgroud.add(txtIdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jpBackgroud.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 350, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/searchgoogle32.png"))); // NOI18N
        jpBackgroud.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 60, -1));

        jLabel3.setText("Quantidade:");
        jpBackgroud.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, -1, -1));

        txtQuantidade.setAlignmentX(0.0F);
        jpBackgroud.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 108, 30, -1));

        jLabel4.setText("Produto:");
        jpBackgroud.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jpBackgroud.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 58, 320, -1));

        txtDataEntrada.setDateFormatString("yyyy-MM-dd");
        jpBackgroud.add(txtDataEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, -1));

        jLabel5.setText("Data Saída:");
        jpBackgroud.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setText("Valor Unitário:");
        jpBackgroud.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 112, -1, -1));
        jpBackgroud.add(txtValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 130, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jpBackgroud.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBackgroud, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        PesquisarProduto();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        NumeroValorUTIL objNumeroValor = new NumeroValorUTIL();
        if (objNumeroValor.validar(txtValorUnitario.getText()) == true) {
            //Recuperar Data
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String DataEntrada = sdf.format(txtDataEntrada.getDate());
            JOptionPane.showMessageDialog(null, DataEntrada);

        } else {
            JOptionPane.showMessageDialog(null, "O valor Unitário deve ser somente numérico e separado por ponto no lugar da vígula");

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int indicelinha = tabela.getSelectedRow();
        txtIdProduto.setText(tabela.getValueAt(indicelinha, 0).toString());
        txtProduto.setText(tabela.getValueAt(indicelinha, 1).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaidaProdutoVIEW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaidaProdutoVIEW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaidaProdutoVIEW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaidaProdutoVIEW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSaidaProdutoVIEW1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBackgroud;
    private javax.swing.JTable tabela;
    private com.toedter.calendar.JDateChooser txtDataEntrada;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables
public class CellRenderer extends DefaultTableCellRenderer {

        /**
         *
         */
        private static final long serialVersionUID = 1L;

        public CellRenderer() {
            super();
        }

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            this.setHorizontalAlignment(CENTER);

            return super.getTableCellRendererComponent(table, value, isSelected,
                    hasFocus, row, column);
        }
    }

    /*
    private void listarValoresProdutos() {
        ProdutoDAO objProdutoDAO = new ProdutoDAO();
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        ArrayList<ProdutoDTO> listaProduto = objProdutoDAO.PesquisarProduto();
        for (int num = 0; num < listaProduto.size(); num++) {
            model.addRow(new Object[]{
                listaProduto.get(num).getPro_id(),
                listaProduto.get(num).getPro_descricao(),
                listaProduto.get(num).getPro_estoque_minimo(),
                listaProduto.get(num).getPro_estoque_maximo()

            });

        }
    }
     */
    private void PesquisarProduto() {
        String sql = "SELECT `pro_id` AS ID,`pro_descricao` AS Produto FROM `tbl_produto` WHERE `pro_status`='Ativado' and `pro_descricao` LIKE ?;";
        try {
            Connection Conn = new ModuloConexao().conectar();
            PreparedStatement pst = Conn.prepareStatement(sql);
            //passando o conteúdo da caixa de pesquisa para o ?
            //atenção ao '%' - continuação da string sql
            pst.setString(1, txtPesquisa.getText() + "%");
            ResultSet rs = pst.executeQuery();
            //a linha abaixo usa a biblioteca rs2xml.jar pra preencher a tabela
            tabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "frmEntradaProdutoVIEW: " + erro);
        }
    }

}
